### ISSUE TITLE
`serialise` benchmarks fail to compile with GHC 9.0 or later

### ISSUE THREAD

**Issue by RyanGlScott** [well-typed/cborg#281]
```
$ cabal build bench:micro bench:versus --enable-tests --enable-benchmarks -w ghc-9.0.2
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - serialise-0.2.4.0 (bench:micro) (first run)
 - serialise-0.2.4.0 (bench:versus) (first run)
Preprocessing benchmark 'micro' for serialise-0.2.4.0..
Preprocessing benchmark 'versus' for serialise-0.2.4.0..
Building benchmark 'micro' for serialise-0.2.4.0..
Building benchmark 'versus' for serialise-0.2.4.0..
[ 6 of 14] Compiling Micro.PkgAesonTH ( bench/micro/Micro/PkgAesonTH.hs, /home/rscott/Documents/Hacking/Haskell/cborg/dist-newstyle/build/x86_64-linux/ghc-9.0.2/serialise-0.2.4.0/b/micro/build/micro/micro-tmp/Micro/PkgAesonTH.o, /home/rscott/Documents/Hacking/Haskell/cborg/dist-newstyle/build/x86_64-linux/ghc-9.0.2/serialise-0.2.4.0/b/micro/build/micro/micro-tmp/Micro/PkgAesonTH.dyn_o )
[ 6 of 15] Compiling Macro.PkgAesonTH ( bench/versus/Macro/PkgAesonTH.hs, /home/rscott/Documents/Hacking/Haskell/cborg/dist-newstyle/build/x86_64-linux/ghc-9.0.2/serialise-0.2.4.0/b/versus/build/versus/versus-tmp/Macro/PkgAesonTH.o, /home/rscott/Documents/Hacking/Haskell/cborg/dist-newstyle/build/x86_64-linux/ghc-9.0.2/serialise-0.2.4.0/b/versus/build/versus/versus-tmp/Macro/PkgAesonTH.dyn_o )

bench/micro/Micro/PkgAesonTH.hs:12:13: error:
    • No instance for (ToJSON Tree) arising from a use of ‘encode’
      There are instances for similar types:
        instance ToJSON v => ToJSON (containers-0.6.4.1:Data.Tree.Tree v)
          -- Defined in ‘aeson-2.0.3.0:Data.Aeson.Types.ToJSON’
    • In the expression: encode
      In an equation for ‘serialise’: serialise = encode
   |
12 | serialise = Aeson.encode
   |             ^^^^^^^^^^^^

bench/micro/Micro/PkgAesonTH.hs:15:26: error:
    • No instance for (FromJSON Tree) arising from a use of ‘decode'’
      There are instances for similar types:
        instance FromJSON v =>
                 FromJSON (containers-0.6.4.1:Data.Tree.Tree v)
          -- Defined in ‘aeson-2.0.3.0:Data.Aeson.Types.FromJSON’
    • In the second argument of ‘(.)’, namely ‘decode'’
      In the expression: fromJust . decode'
      In an equation for ‘deserialise’: deserialise = fromJust . decode'
   |
15 | deserialise = fromJust . Aeson.decode'
   |                          ^^^^^^^^^^^^^

bench/versus/Macro/PkgAesonTH.hs:12:18: error:
    • No instance for (ToJSON GenericPackageDescription)
        arising from a use of ‘encode’
    • In the expression: encode pkgs
      In an equation for ‘serialise’: serialise pkgs = encode pkgs
   |
12 | serialise pkgs = Aeson.encode pkgs
   |                  ^^^^^^^^^^^^^^^^^

bench/versus/Macro/PkgAesonTH.hs:15:26: error:
    • No instance for (FromJSON GenericPackageDescription)
        arising from a use of ‘decode'’
    • In the second argument of ‘(.)’, namely ‘decode'’
      In the expression: fromJust . decode'
      In an equation for ‘deserialise’: deserialise = fromJust . decode'
   |
15 | deserialise = fromJust . Aeson.decode'
   |                          ^^^^^^^^^^^^^
cabal: Failed to build bench:micro from serialise-0.2.4.0.
Failed to build bench:versus from serialise-0.2.4.0.
```

This can likely be fixed by changing the order of TH splices.
