### ISSUE TITLE
Fails to build with ghcjs-8.4

### ISSUE THREAD

**Issue by matthewbauer** [well-typed/cborg#198]
I'm getting this compiling cborg for ghcjs:

```
src/Codec/CBOR/Read.hs:368:29: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        p2 :: *
        Word# :: TYPE 'WordRep
    • In the first argument of ‘w_out_of_range’, namely ‘w#’
      In the expression: w_out_of_range w#
      In the expression:
        case w_out_of_range w# of
          0#
            | isWordCanonical sz w# -> k w# >>= go_fast (BS.unsafeDrop sz bs)
          _ -> go_fast_end bs da
    |
368 |         case w_out_of_range w# of
    |                             ^^

src/Codec/CBOR/Read.hs:413:29: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        p3 :: *
        Int# :: TYPE 'IntRep
    • In the first argument of ‘n_out_of_range’, namely ‘n#’
      In the expression: n_out_of_range n#
      In the expression:
        case n_out_of_range n# of
          0# | isIntCanonical sz n# -> k n# >>= go_fast (BS.unsafeDrop sz bs)
          _ -> go_fast_end bs da
    |
413 |         case n_out_of_range n# of
    |                             ^^

src/Codec/CBOR/Read.hs:482:9: error:
    • Couldn't match expected type ‘Bool’
                  with actual type ‘Int -> Word64# -> Bool’
    • Probable cause: ‘isWord64Canonical’ is applied to too few arguments
      In the expression: isWord64Canonical
      In a stmt of a pattern guard for
                     a case alternative:
        isWord64Canonical
      In a case alternative:
          DecodedToken sz (W64# w#)
            | isWord64Canonical -> k w# >>= go_fast (BS.unsafeDrop sz bs)
            | otherwise -> go_fast_end bs da
    |
482 |       | isWord64Canonical -> k w# >>= go_fast (BS.unsafeDrop sz bs)
    |         ^^^^^^^^^^^^^^^^^

src/Codec/CBOR/Read.hs:504:31: error:
    • Variable not in scope: int64ToWord64 :: Int64# -> Word64#
    • Perhaps you meant ‘int64ToWord64#’ (imported from GHC.IntWord64)
    |
504 |       | isWord64Canonical sz (int64ToWord64 i#) -> k i# >>= go_fast (BS.unsafeDrop sz bs)
    |                               ^^^^^^^^^^^^^

src/Codec/CBOR/Read.hs:512:31: error:
    • Variable not in scope: int64ToWord64 :: Int64# -> Word64#
    • Perhaps you meant ‘int64ToWord64#’ (imported from GHC.IntWord64)
    |
512 |       | isWord64Canonical sz (int64ToWord64 i#) -> k i# >>= go_fast (BS.unsafeDrop sz bs)
    |                               ^^^^^^^^^^^^^

src/Codec/CBOR/Read.hs:806:54: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        p0 :: *
        Word# :: TYPE 'WordRep
    • In the first argument of ‘w_out_of_range’, namely ‘w#’
      In the expression: w_out_of_range w#
      In the expression:
        case w_out_of_range w# of
          0#
            | isWordCanonical sz w#
            -> k w# >>= go_fast_end (BS.unsafeDrop sz bs)
            | otherwise -> return $! SlowFail bs "non-canonical word32"
          _ -> return $! SlowFail bs "expected word32"
    |
806 |       DecodedToken sz (W# w#) -> case w_out_of_range w# of
    |                                                      ^^

src/Codec/CBOR/Read.hs:854:29: error:
    • Couldn't match a lifted type with an unlifted type
      When matching types
        p1 :: *
        Int# :: TYPE 'IntRep
    • In the first argument of ‘n_out_of_range’, namely ‘n#’
      In the expression: n_out_of_range n#
      In the expression:
        case n_out_of_range n# of
          0#
            | isIntCanonical sz n#
            -> k n# >>= go_fast_end (BS.unsafeDrop sz bs)
            | otherwise -> return $! SlowFail bs "non-canonical int32"
          _ -> return $! SlowFail bs "expected int32"
    |
854 |         case n_out_of_range n# of
    |                             ^^

src/Codec/CBOR/Read.hs:1361:40: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the second argument of ‘leWord64#’, namely ‘0x17##’
      In the first argument of ‘isTrue#’, namely
        ‘(w# `leWord64#` 0x17##)’
      In the second argument of ‘(&&)’, namely
        ‘isTrue# (w# `leWord64#` 0x17##)’
     |
1361 |   | sz == 2 && isTrue# (w# `leWord64#` 0x17##)       = False
     |                                        ^^^^^^

src/Codec/CBOR/Read.hs:1362:40: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the second argument of ‘leWord64#’, namely ‘0xff##’
      In the first argument of ‘isTrue#’, namely
        ‘(w# `leWord64#` 0xff##)’
      In the second argument of ‘(&&)’, namely
        ‘isTrue# (w# `leWord64#` 0xff##)’
     |
1362 |   | sz == 3 && isTrue# (w# `leWord64#` 0xff##)       = False
     |                                        ^^^^^^

src/Codec/CBOR/Read.hs:1363:40: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the second argument of ‘leWord64#’, namely ‘0xffff##’
      In the first argument of ‘isTrue#’, namely
        ‘(w# `leWord64#` 0xffff##)’
      In the second argument of ‘(&&)’, namely
        ‘isTrue# (w# `leWord64#` 0xffff##)’
     |
1363 |   | sz == 5 && isTrue# (w# `leWord64#` 0xffff##)     = False
     |                                        ^^^^^^^^

src/Codec/CBOR/Read.hs:1364:40: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the second argument of ‘leWord64#’, namely ‘0xffffffff##’
      In the first argument of ‘isTrue#’, namely
        ‘(w# `leWord64#` 0xffffffff##)’
      In the second argument of ‘(&&)’, namely
        ‘isTrue# (w# `leWord64#` 0xffffffff##)’
     |
1364 |   | sz == 9 && isTrue# (w# `leWord64#` 0xffffffff##) = False
     |                                        ^^^^^^^^^^^^

src/Codec/CBOR/Read.hs:1370:14: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int64#’
    • In the first argument of ‘(<#)’, namely ‘i#’
      In the first argument of ‘isTrue#’, namely ‘(i# <# 0#)’
      In the expression: isTrue# (i# <# 0#)
     |
1370 |   | isTrue# (i# <# 0#) = isWord64Canonical sz (not64# w#)
     |              ^^
```

**Comment by matthewbauer** [comment]
This was on cborg-0.2.0.0. Bumping to cborg-0.2.1.0 seems to fix it
