### PR TITLE
serialise: Fix build with quickcheck-instances-0.3.32

### PR DESCRIPTION
**Pull request by 9999years**
Closes https://github.com/well-typed/cborg/issues/340

Fixes a build error due to overlapping instances:

```
[13 of 14] Compiling Tests.Serialise  ( tests/Tests/Serialise.hs, dist/build/tests/tests-tmp/Tests/Serialise.o )

tests/Tests/Serialise.hs:283:9: error: [GHC-43085]
    • Overlapping instances for Arbitrary (Vector.Primitive.Vector Int)
        arising from a use of ‘mkTest’
      Matching instances:
        instance (Vector.Primitive.Prim a, Arbitrary a) =>
                 Arbitrary (Vector.Primitive.Vector a)
          -- Defined in ‘Test.QuickCheck.Instances.Vector’
        instance (Vector.Primitive.Prim a, Arbitrary a) =>
                 Arbitrary (Vector.Primitive.Vector a)
          -- Defined at tests/Tests/Orphanage.hs:198:10
    • In the expression: mkTest (T :: T (Vector.Primitive.Vector Int))
      In the second argument of ‘testGroup’, namely
        ‘[mkTest (T :: T ()), mkTest (T :: T Bool), mkTest (T :: T Int),
          mkTest (T :: T Int8), ....]’
      In the expression:
        testGroup
          "Simple instance invariants"
          [mkTest (T :: T ()), mkTest (T :: T Bool), mkTest (T :: T Int),
           mkTest (T :: T Int8), ....]
    |
283 |       , mkTest (T :: T (Vector.Primitive.Vector Int))
    |         ^^^^^^
```

### CODE REVIEW

**Comment by bgamari** [comment]
Thanks @9999years! I fixed this in #341 .
